{
 "title": "Event-Manager dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Error rate (5xx), %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_server_request_duration_seconds_count{http_response_status_code=~\"5..\"}[$__rate_interval]))\r\n  / sum(rate(http_server_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count of exceptions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_exceptions_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (p50, p95, p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket[$__rate_interval])) by (le)) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests in processing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "http_server_active_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request rate by route",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}