<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
      <UserSecretsId>25c4d7fa-acbc-40c5-8342-4a421791b217</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10" />
      <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\EventManager.Application\EventManager.Application.csproj" />
      <ProjectReference Include="..\EventManager.Infrastructure\EventManager.Infrastructure.csproj" />
    </ItemGroup>

</Project>
