<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
        <UserSecretsId>ec69edc4-8c4e-4a35-908e-ae188ba85497</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.19.0" />
      <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.19.0-beta.1" />
      <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.19.0" />
      <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.19.0" />
      <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.19.0-beta.1" />
      <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.19.0" />
      <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.19.0" />
      <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
      <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
      <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Event.Application\Event.Application.csproj" />
      <ProjectReference Include="..\Event.Infrastructure\Event.Infrastructure.csproj" />
    </ItemGroup>

</Project>
